### ISSUE TITLE
Official SDK?

### ISSUE THREAD

**Issue by GGB1977** [italia/verificac19-sdk#1]
@astagi: Ottimo lavoro, gran cosa! Solo una piccolo dubbio.. anche questo è un SDK "UFFICIALE" come quello Android o è un progetto personale? Lo chiedo perché non è tra i repo del Ministero.... In ogni caso grazie

**Comment by astagi** [comment]
Ciao @GGB1977 grazie! Ho fatto la procedura di onboarding per renderlo un SDK ufficiale, appena ho notizie ti aggiorno :)

**Comment by astagi** [comment]
PR linked https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding/pull/3

**Comment by dcannova** [comment]
> Ciao @GGB1977 grazie! Ho fatto la procedura di onboarding per renderlo un SDK ufficiale, appena ho notizie ti aggiorno :)

Quindi, supponendo la procedura di onboarding abbia successo, sarà sufficiente aver incluso ed utilizzato le primitive di questo package **verificac19-sdk** per essere completamente in regola? Oppure verrà spostato da qualche altra parte con un nome diverso etc...?
Lo chiedo in anticipo così almeno comincio ad integrarlo.
Grazie.

**Comment by astagi** [comment]
@dcannova esatto! non ci sarà alcuno spostamento, il repo rimarrà qua così come il nome e il package npm.

**Comment by lucavicari** [comment]
Salve, vedo che il repository non è ancora entrato nella lista degli sdk "ufficiali", ci sono novità in merito?ù
Grazie mille

**Comment by GGB1977** [comment]
Ciao @astagi, anche io stavo per fare la stessa domanda di @luca-vix, ci sono problemi? 

Secondo te se commentiamo qui:

https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding/pull/3

c'e' possibilità di sbloccare/accelerare la richiesta di Review?

**Comment by astagi** [comment]
@GGB1977 @luca-vix si, sicuramente un po' di pressione con i commenti potrebbe aiutare! Grazie mille!

**Comment by GGB1977** [comment]
Noi ci abbiamo provato ora stiamo a vedere... ;)

**Comment by astagi** [comment]
Grazie ragazzi!

**Comment by astagi** [comment]
@luca-vix @dcannova @GGB1977 ci siamo, grazie e buona implementazione 🙌
