### ISSUE TITLE
Green pass revocati

### ISSUE THREAD

**Issue by valeprog** [italia/verificac19-sdk#18]
# Issue content
Come si verifica se un green pass è stato revocato o meno? Intendo revocato anche per chi diventa positivo... Da quanto ho capito l'ultima versione di VerificaC19 permette di scaricare la lista delle certificazioni revocate.

**Comment by mastro993** [comment]
Ciao @valeprog!

Ll'SDK permette già lo scaricamento e caching della lista dei certificati revocati, quindi la normale procedura di verifica di un certificato include anche il controllo per la revoca. 
Come da esempio:

```js
// Ottieni il certificat
const myDCC = await Certificate.fromImage('./data/myDCC.png');
// oppure
const myDCC = await Certificate.fromRaw('HC1:6BF+70790T9WJWG.FKY*4GO0.O1CV2...etc..');

// e poi lo validi
const validationResult = await Validator.validate(myDCC);
```
In `validationResult.code` troverai il valore `REVOKED` in caso di certificato revocato.

Assicurati di aver prima aggiornato la relativa lista dei certificati revocati, altrimenti non potrà avvenire il controllo (e la conseguente validazione del certificato).

```js
await Service.updateAll();
```
Spero di esserti stato di aiuto.

**Comment by valeprog** [comment]
Ho un'altra domanda:
i certificati revocati vengono scaricati da quì [](https://get.dgc.gov.it/v1/dgc/settings)?

**Comment by mastro993** [comment]
Si e no: da li viene presa la lista delle regole utilizzata perla validazione, tra cui una la lista degli UVCI (identificativo del certificato) bloccati, ovvero (credo) quei UVCI che sono in circolazione ma che non devono essere riconosciuti per diversi motivi.
Ciò che cerchi tu è la lista dei certificati revocati e riabilitati ed è presa da https://get.dgc.gov.it/v1/dgc/crl.

**Comment by valeprog** [comment]
perfetto grazie!

**Comment by astagi** [comment]
Grazie @mastro993! @valeprog ho rilasciato ieri la versione 0.7.0 dell'SDK con diversi improvement sulla DRL e la nuova modalità booster per qualsiasi domanda relativa apri pure nuove issue. Buon lavoro!
