### ISSUE TITLE
Redis as CRL manager

### ISSUE THREAD

**Issue by Pe46dro** [italia/verificac19-sdk#25]
I made a try to implement a CRL manager with Redis instead of lowdb and the performance i think is even better than MongoDB, I think that you should give a try.
On windows i used memurai as Redis replacement.
 
```js
[...]
  async setUp() {
	const client = createClient();
	client.on('error', (err) => console.log('Redis Client Error', err));
	await client.connect();
	this._db = client;
  }

  async storeRevokedUVCI(revokedUvci) {
	for (const element of revokedUvci) {
		this._db.set(element, 'true');
	}
  }

  async isUVCIRevoked(uvci) {
    return await this._db.get(uvci) || false;
  }

  async clean() {
	return await this._db.sendCommand(['FLUSHDB']);
  }
```

_____________

I also would like to report an issue on the custom CRL manager example:

https://github.com/italia/verificac19-sdk/blob/55a43bd452871684f6632151b549797cab1d34e2/examples/mycrlmanager/index.js#L16

as it should be:

```js
 return !await this._db.get('uvcis').find(uvci); 
```

**Comment by astagi** [comment]
Thank you @Elius94 @Pe46dro I’ll fix it!

@Pe46dro I usually store cache and volatile data on Redis and persistent data on db like MongoDB or PostgreSQL. Anyway I agree with you, Redis is way faster than MongoDB. Why not writing a plugin for VerificaC19 SDK and publish it on NPM? It could be used by developers in place of MongoDB CRL Adapter.
