### ISSUE TITLE
Test Green Pass

### ISSUE THREAD

**Issue by pablosproject** [italia/verificac19-sdk#28]
Is there any Green Pass QR code (or string) usable for testing? We have some integration tests and API monitoring tools that run periodically and do not want to expose the personal information of our developers. Is there such thing as a valid test for Green Pass?

**Comment by albertorizzi** [comment]
Yes @pablosproject, in [test/data](https://github.com/italia/verificac19-sdk/tree/master/test/data) there are some QR code or string usable for testing.

**Comment by pablosproject** [comment]
Thanks

**Comment by pablosproject** [comment]
@albertorizzi is there any example of certificate with TEST_NEEDED, or other cases? I see that in your tests you mock the actual date to get the desired results in tests.
We are trying to build integration test cases to run on our real system and we cannot mock/fake the current date, so having some test certificates will help a lot.

**Comment by astagi** [comment]
@pablosproject creating a payload by yourself and test it could help? I use rewire in my tests to access private methods https://github.com/jhnns/rewire and I can access functions like dccToModel 

- https://github.com/italia/verificac19-sdk/blob/master/test/verification.test.js#L7
- https://github.com/italia/verificac19-sdk/blob/master/test/verification.test.js#L193

This is still a mock, but it doesn't take any effect on system date
