### ISSUE TITLE
updateSignatures function fails for 502 error

### ISSUE THREAD

**Issue by gs-link** [italia/verificac19-sdk#29]
I found that today the function updateSignatures fails for a 502 error on an endpoint. Adding a try/catch block is preventing the error, maybe it's just an error due to a invalid endpoint, but it should be managed.

Thank you

Sebastiano

**Comment by astagi** [comment]
Hi @gs-link thank you! The problem on server should be fixed now. 

If you want to contribute, feel free to open a PR to manage errors thrown by updateAll method
