### ISSUE TITLE
Modalità work e Gestione Green Pass over 50

### ISSUE THREAD

**Issue by GGB1977** [italia/verificac19-sdk#31]
ciao @astagi,
per quanto riguarda la modalità di validazione "work" (vedi app Verifica C19), con la gestione degli over 50, avete in programma di rilasciarla prima del 15 o conviene iniziare integrarla manualmente  nei singoli progetti facendo un controllo sulla data i nascita?
Nessuna pressione è solo per sapere come muovermi... ;)
Grazie
Ciao

**Comment by depontimatteo** [comment]
Ciao @astagi, anche qui siamo in trepidante attesa... Riesci a farci sapere se riuscite ad uscire in tempo con modalità SCHOOL e WORK o se dobbiamo temporaneamente gestirla lato singolo progetto?
Grazie,
Ciao

**Comment by astagi** [comment]
Ciao @depontimatteo @GGB1977 la rilascio entro la giornata di domani insieme agli altri cambiamenti :) scusate il ritardo

**Comment by depontimatteo** [comment]
Grazie @astagi, allora aspetto il tuo rilascio. Grazie per l'enorme lavoro che stai facendo

**Comment by astagi** [comment]
Sono andato un po' lungo @depontimatteo @GGB1977 ho dovuto incastrare diverse cose in questi giorni di fuoco :) in ogni caso ci siamo quasi, sul branch dedicato (https://github.com/italia/verificac19-sdk/pull/32) c'è già l'implementazione pronta seguendo le ultime specifiche (ahimè priva di refactoring, ma arriverà anche quello). Cosa più importante adesso prima del rilascio ufficiale è scrivere dei test minuziosi per verificare che sia tutto ok. Se già volete fare alcune prove voi mergiando il branch in questione ben venga, ogni aiuto è prezioso!
