### ISSUE TITLE
Verification with Validator.validate() during Service.updateAll() ?

### ISSUE THREAD

**Issue by bluepuma77** [italia/verificac19-sdk#34]
We build a web service that checks certificates with [verificac19-sdk](https://github.com/italia/verificac19-sdk). It seems that a call to `await Service.updateAll()` is blocking validation at the same time, even when MongoDB database and cache files are present.
```
Signature ERROR: certificate can't be verified, undefined
Rules ERROR: certificate can't be verified, undefined
Validation ERROR: certificate can't be verified, undefined
```
Can you confirm that we can not use `Validator.validate()` at the same time while `Service.updateAll()` is still running? 

We saw that `updateAll()` sometimes takes minutes to finish, then we need to find a workaround to be able to continue processing incoming verification requests (load balancer, separate instances, closing port during update, etc.).

**Comment by astagi** [comment]
Hi @bluepuma77, sure that error is thrown when cache is not ready, e.g.

- cache files are missing (that's not the case
- CRL is not updated (download in progress)

How many times you call updateAll?

**Comment by bluepuma77** [comment]
`updateAll()` is called when the instance starts and every 24h again. Just wanted to make sure.

I guess we will only open the listening port when the update after startup is finished and exit the container after 24h. 

With multiple containers in a service, the load balancer should always route requests to a working container.

**Comment by astagi** [comment]
It should work @bluepuma77 , let me know!
