### ISSUE TITLE
è giusto settare endNow in questa maniera, diversamente da startNow?

### ISSUE THREAD

**Issue by st4nny** [italia/verificac19-sdk#41]
https://github.com/italia/verificac19-sdk/blob/63267988b654b10ee78f9ec1e6de3761b7f4324e/src/validator.js#L149

Oggi ho ricevuto, valutando una certificazione, con sdk attuale: 
NOT_VALID - Vaccination format is invalid
con
startDate: 2021-09-15T00:00:00.000Z
endDate: 2022-03-14T00:00:00.000Z
endNow: 2022-03-14T23:59:59.999Z

chiaramente settando: endNow.setUTCHours(0, 0, 0, 0);
la validazione passa.
Lo stesso certificato valutato con VerificaC19 e sdk php viene verificato normalmente.
Chi sbaglia? 

Un saluto

**Comment by astagi** [comment]
Rilasciata versione con fix
