### ISSUE TITLE
Verifica del vaccino Novavax non valida

### ISSUE THREAD

**Issue by jam830** [italia/verificac19-sdk#43]
**Describe the bug**
Quando viene inviata alla libreria un QR-Code di un vaccinato con Novavax (Nuvaxoid) da più di 15 giorno, quindi valido, l'sdk ritorna: "Not EMA vaccine is not valid for worker with age < 50 years".

Il QR-Code verificato con l'app cverifica-19 risulta funzionare correttamente.

**To Reproduce**
1. Verificare un certificato di un utente vaccinato con Novavax (Nuvaxoid) 
2. See error

**Comment by DevPGS** [comment]
see #38,
nel source code non è presente il nuovo codice per Nuvaxoid [EU/1/21/1618], che invece è disponibile nei settings di dcg.

[settings](https://get.dgc.gov.it/v1/dgc/settings)
```json
{"name":"EMA_vaccines","type":"GENERIC","value":"EU/1/20/1525;EU/1/20/1507;EU/1/20/1528;EU/1/21/1529;Covishield;R-COVI;Covid-19-recombinant;EU/1/21/1618"}
```
[validator.js](https://github.com/italia/verificac19-sdk/blob/master/src/validator.js)
```javascript
const JOHNSON = 'EU/1/20/1525';
const SPUTNIK = 'Sputnik-V';
const MODERNA = 'EU/1/20/1507';
const PFIZER = 'EU/1/20/1528';
const ASTRAZENECA = 'EU/1/21/1529';
const COVISHIELD = 'Covishield';
const R_COVI = 'R-COVI';
const COVID19_RECOMBINANT = 'Covid-19-recombinant';

const VACCINES_EMA_LIST = [JOHNSON, MODERNA, PFIZER, ASTRAZENECA, COVISHIELD, R_COVI, COVID19_RECOMBINANT];
```

**Comment by astagi** [comment]
Grazie della segnalazione @jam830 entro domani rilascio il fix! @DevPGS per la #38 ci lavorerò nei prossimi giorni :)

**Comment by astagi** [comment]
Rilasciata versione con fix

**Comment by jam830** [comment]
Fantastico, grazie mille!
