### ISSUE TITLE
Cache is not ready!

### ISSUE THREAD

**Issue by st4nny** [italia/verificac19-sdk#48]
Ciao da ieri, effettuando dei test con l'ultima versione ottengo:

Processing new request... (node:2173378) UnhandledPromiseRejectionWarning: CertificateVerificationError: certificate can't be verified, undefined
    at checkCacheIsReady (/home/test/sdk-0.9.4/node_modules/verificac19-sdk/src/validator.js:663:11)
    at checkSignature (/home/test/sdk-0.9.4/node_modules/verificac19-sdk/src/validator.js:712:3)
    at Object.validate (/home/test/sdk-0.9.4/node_modules/verificac19-sdk/src/validator.js:743:29)
    at Server.<anonymous> (/home/test/sdk-0.9.4/app.js:105:44)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2173378) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2173378) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

La versione di node è la v14.19.1, a cosa può essere dovuto?

**Comment by astagi** [comment]
ciao @st4nny è dovuto al fatto che il SDK non riesce a leggere la cache. I file di cache devono essere presenti all'avvio della verifica.

**Comment by st4nny** [comment]
Ciao @astagi grazie per la risposta.
La cosa strana è che avevo sia la cartella .cache con i 4 file presenti e sia la crl scaricata,
questa cosa mi è successa su due ambienti distinti più o meno nello stesso arco temporale.
Oggi ho rifatto un giro di test e tutto funziona regolarmente.

Un saluto

**Comment by astagi** [comment]
Si evidentemente ancora non era pronta :) comunque ok per chiudere la issue se si ripresenta segnalamelo pure!

Grazie!

Saluti e buon weekend!
