### ISSUE TITLE
Comment faire ?

### ISSUE THREAD

**Issue by FULCOS** [italia/verificac19-sdk#5]
Bonjour, je n'arrive pas a comprendre comment cela marche, j'aimerais crée un passe sanitaire mais je ne sais pas du coup comment le script marche, qui pourrais m'aider s'il vous plait.

**Comment by FULCOS** [comment]
Ciao, non capisco come funziona, vorrei creare un pass sanitario valido ma non so come funziona lo script, che potrebbe aiutarmi per favore.

**Comment by astagi** [comment]
@FULCOS questa libreria valida i pass, non li crea.

Saluti

**Comment by FULCOS** [comment]
Ciao, puoi dirmi come farlo per favore perché sono nuovo di JavaScript?

**Comment by astagi** [comment]
Per creare un certificato valido occorre firmarlo con le chiavi in possesso delle autorità competenti. La creazione di certificati non è scopo di questo progetto e la creazione di certificati falsi è perseguibile dalla legge.

**Comment by FULCOS** [comment]
So che voglio solo divertirmi a creare passaggi divertenti ma non so come funziona lo script.

Non voglio usare questo script per scopi illegali!

**Comment by FULCOS** [comment]
Mi potete aiutare ?

**Comment by astagi** [comment]
@FULCOS ti ho risposto nell'altro thread. Prova a partire da README e esempi, scrivi qualche porzione di codice. Prova anche a leggere la documentazione del DCC https://github.com/ministero-salute/it-dgc-documentation

**Comment by FULCOS** [comment]
Ho cercato di trovare una soluzione per 2 giorni, ma sono nuovo di JavaScript e non sono sicuro di come farlo.

Aiutami per favore, puoi darmi i passaggi per favore?

**Comment by astagi** [comment]
Hai provato a seguire il README? Se non fai vedere dove ti sei bloccato è difficile poterti aiutare
