### ISSUE TITLE
Discrepanza con app c19

### ISSUE THREAD

**Issue by steve6** [italia/verificac19-sdk#51]
**Describe the bug**
Sto provando a validare un GP, su app c19 risulta valido con modalità rafforzato mentre attraverso il test con questo modulo risulta scaduto 2 giorni fa.

```
{
  person: '------',
  date_of_birth: '1987-07-21',
  result: false,
  code: 'NOT_VALID',
  message: 'Doses 2/1 - Vaccination is expired at : 2022-04-24T00:00:00.000Z'
}
```

Il vaccino è PFIZER e la regola per il calcolo dei giorni di validità prende 180.

Posso condividere il caso in privato.

**Comment by steve6** [comment]
Credo di aver capito l'errore confrontando l'SDK android

Queste due linee di codice sono diverse (AND al POSTO di OR)
https://github.com/italia/verificac19-sdk/blob/master/src/validator.js#L171
https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/blob/develop/sdk/src/main/java/it/ministerodellasalute/verificaC19sdk/model/CertificateModel.kt#L97

**Comment by astagi** [comment]
@steve6 grazie del report in giornata controllo tutto :) nel caso ti contatto privatamente per risolvere il problema, grazie!
