### ISSUE TITLE
Come usarlo

### ISSUE THREAD

**Issue by FULCOS** [italia/verificac19-sdk#6]
# Issue content
Hello, I am new to JavaScript and would like to know how it works

Ciao, sono nuovo di JavaScript e vorrei sapere come funziona

**Comment by astagi** [comment]
@FULCOS questa libreria permette la validazione degli EU DCC, puoi partire dalla cartella `examples` oppure dal README per capire come fare un iniziale setup. Per qualsiasi blocco prova a riportare il codice che stai utilizzando.
